## Numpy in Python: Advanced

#### Numpy is a library for the Python programming languge. It supports fast computation for large multidimensional arrays and offers a wide collection of high-level mathematical functions. It is essential for Data science and used very often in Machine and Deep learning. 

In [1]:
# Import Numpy library
import numpy as np 

In [2]:
# Define one-dimensional numpy array
first_array = np.array([1, 2, 3, 4, 5, 6])
first_array

array([1, 2, 3, 4, 5, 6])

In [4]:
#Define two-Dimeensional numpy array
second_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
second_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

#### Accessing specific element

In [8]:
# Accessing element from 2D array: 0th row
second_array[0,]

array([1, 2, 3])

In [10]:
# Accessing element from 2D array: 0th row and second column eement
second_array[0,1]

2

In [11]:
# Accessing element from 2D array: 3th row and 3rd column elment
second_array[2,2]

9

#### Special Arrays with Numpy
###### Mention zeros, ones, and eye function in Numpy

#### Call "zeros" function to define an array/matrix of zero element.

In [12]:
# Define zeros array
zero_array = np.zeros(5)
zero_array

array([0., 0., 0., 0., 0.])

In [14]:
# Define zeros 4-by-4 matrix
zero_matrix = np.zeros((4,4))
zero_matrix

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

#### Call "ones" function to define an array/matrix of 1 element.

In [15]:
# Define ones array
ones_array = np.ones(6)
ones_array

array([1., 1., 1., 1., 1., 1.])

In [16]:
# Define ones matrix
ones_matrix = np.ones((4,4))
ones_matrix

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

#### Call "eye" function to define a matrix.

In [17]:
# Define eye matrix
eye_matrix = np.eye(3)
eye_matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Arrays with Special Methods

#### Call arange() function 

In [22]:
# define arange function: where 0 is initial bound and 10 is upper bound
arange_array = np.arange(1, 10)
arange_array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
# print odd number: using arange()
Odd_arange_array = np.arange(1, 10, 2)
Odd_arange_array

array([1, 3, 5, 7, 9])

In [26]:
# print even number: using arange()
Even_arange_array = np.arange(1, 10, 3)
Even_arange_array

array([1, 4, 7])

#### Call linspace() function

In [29]:
# linspace means divide interval equally using last argument say 5
linspace_array  = np.linspace(0, 100, 5)
linspace_array

array([  0.,  25.,  50.,  75., 100.])

#### Random Module: "Random" is a special module in the Numpy library. It will create floating point numbers betwwen 0 and 1. the range is in Standard normal distribution.

In [32]:
# Define five random number between 0 and 1. 
random_number = np.random.rand(5)
random_number

array([0.9964458 , 0.36312746, 0.69020061, 0.22784709, 0.23369205])

In [35]:
# Create one random number
one_random_number = np.random.randint(0, 100)
one_random_number

63

In [36]:
# Create 5 random number at a time:
five_random_number = np.random.randint(0, 100, 5)
five_random_number

array([ 7, 58, 23, 48, 75])

#### Special functions of the Numpy arrays: sum(), min(), max(), std(), var()...

In [38]:
# create 10 random numbers
ten_guessing_number = np.random.randint(1, 100, 10)
ten_guessing_number

array([ 3, 89,  2, 54, 49, 93, 18,  3, 66,  9])

In [39]:
# sum of ten random numbers
ten_guessing_number.sum()

386

In [41]:
# Maximum of ten random numbers:
ten_guessing_number.max()

93

In [42]:
# Minimum of ten random numbers:
ten_guessing_number.min()

2

In [43]:
# STD of ten random numbers:
ten_guessing_number.std()

34.30801655590133

In [44]:
# Varience of ten random numbers:
ten_guessing_number.var()

1177.04

In [45]:
# argmax of ten random numbers: Index of the biggest element
ten_guessing_number.argmax()

5

In [47]:
# argmax of ten random numbers: Index of the minimum element
ten_guessing_number.argmin()

2

#### Random creation using array

In [48]:
# gussing any 3 random number from a array
ten_guessing_number[:3]

array([ 3, 89,  2])

In [49]:
# gussing any random number from a array
ten_guessing_number[1:3]

array([89,  2])

#### Mathematical Operation

In [50]:
# Define two array
array1 = np.array([1,2,3,4,5,6,7,8,9])
array2 = np.array([11,12,13,14,15,16, 17,18,19])

# now add two array:
arraysum = array1 + array2
arraysum

array([12, 14, 16, 18, 20, 22, 24, 26, 28])

In [53]:
# subtraction of two arrays
arraysub = array1 - array2
arraysub

array([-10, -10, -10, -10, -10, -10, -10, -10, -10])

In [54]:
# multiplication of two arrays
arraymul = array1 * array2
arraymul

array([ 11,  24,  39,  56,  75,  96, 119, 144, 171])

In [56]:
# multiplication of two arrays
arraymul = (3*array1) * array2
arraymul

array([ 33,  72, 117, 168, 225, 288, 357, 432, 513])

In [55]:
# division of two arrays
arraydiv = array1 / array2
arraydiv

array([0.09090909, 0.16666667, 0.23076923, 0.28571429, 0.33333333,
       0.375     , 0.41176471, 0.44444444, 0.47368421])

### Some Projects using Numpy

### This tutorial design by Khalid Hossen